version: '3.8'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: makszakharov/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: makszakharov/kittygram_frontend
    volumes:
      - static:/static

  gateway:
    image: makszakharov/kittygram_gateway
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
